### ISSUE TITLE
最新版本运行出错（非Docker）

### ISSUE THREAD

**Issue by flower-elf** [6mb/Microsoft-365-Admin#33]
配置文件均检查过没有问题，在发生问题之后我还使用默认配置文件（zip里面提供的）运行了一遍，结果报相同错误
由于只是进行本地快速管理，所以没有使用docker
环境：非Docker，Windows 11 Dev 22000.65
命令行：java -jar "文件路径" --spring.profile.active=dev
Java版本：1.8.0_281-b09
错误描述：
**org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphCache': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'graph.cache.timeout.user' in value "${graph.cache.timeout.user}"**
启动日志
```
2021-07-10 23:53:11.674  INFO 9788 --- [           main] cn.itbat.microsoft.MicrosoftApplication  : Starting MicrosoftApplication v1.6.2-RELEASE using Java 1.8.0_281 on rain-workpc with PID 9788 (E:\system\Users\rain\Downloads\admin-portal\microsoft-365-admin-1.6.2-RELEASE.jar started by rain in C:\Users\rain)
2021-07-10 23:53:11.677  INFO 9788 --- [           main] cn.itbat.microsoft.MicrosoftApplication  : The following profiles are active: dev
2021-07-10 23:53:14.148  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-07-10 23:53:14.153  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-07-10 23:53:14.590  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 414 ms. Found 1 JPA repository interfaces.
2021-07-10 23:53:14.634  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-07-10 23:53:14.636  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2021-07-10 23:53:14.675  INFO 9788 --- [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface cn.itbat.microsoft.repository.InvitationCodeRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.
2021-07-10 23:53:14.675  INFO 9788 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 19 ms. Found 0 Redis repository interfaces.
2021-07-10 23:53:16.265  INFO 9788 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8099 (http)
2021-07-10 23:53:16.293  INFO 9788 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-07-10 23:53:16.293  INFO 9788 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.45]
2021-07-10 23:53:16.458  INFO 9788 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-07-10 23:53:16.458  INFO 9788 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4648 ms
2021-07-10 23:53:16.884  INFO 9788 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-07-10 23:53:17.508  INFO 9788 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-07-10 23:53:17.636  INFO 9788 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-07-10 23:53:17.893  INFO 9788 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.30.Final
2021-07-10 23:53:18.265  INFO 9788 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2021-07-10 23:53:18.635  INFO 9788 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2021-07-10 23:53:19.944  INFO 9788 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-07-10 23:53:19.964  INFO 9788 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-07-10 23:53:20.013  WARN 9788 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphCache': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'graph.cache.timeout.user' in value "${graph.cache.timeout.user}"
2021-07-10 23:53:20.013  INFO 9788 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-07-10 23:53:20.014  INFO 9788 --- [           main] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2021-07-10 23:53:20.022  INFO 9788 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-07-10 23:53:20.024  INFO 9788 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2021-07-10 23:53:20.027  INFO 9788 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-07-10 23:53:20.037  INFO 9788 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-07-10 23:53:20.080 ERROR 9788 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphCache': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'graph.cache.timeout.user' in value "${graph.cache.timeout.user}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
        at cn.itbat.microsoft.MicrosoftApplication.main(MicrosoftApplication.java:17) [classes!/:1.6.2-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_281]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [microsoft-365-admin-1.6.2-RELEASE.jar:1.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [microsoft-365-admin-1.6.2-RELEASE.jar:1.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [microsoft-365-admin-1.6.2-RELEASE.jar:1.6.2-RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [microsoft-365-admin-1.6.2-RELEASE.jar:1.6.2-RELEASE]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'graph.cache.timeout.user' in value "${graph.cache.timeout.user}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1321) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.6.jar!/:5.3.6]
        ... 26 common frames omitted

```

**Comment by flower-elf** [comment]
可能与 #31 相似（错误不同），但经查应该不是配置文件问题

**Comment by flower-elf** [comment]
看起来似乎是这个配置的问题
![图片](https://user-images.githubusercontent.com/47104993/125169270-f3d76880-e1db-11eb-9c5d-74cc8d4c8d50.png)
但是我没有对这个配置作出任何修改

**Comment by 6mb** [comment]
你尝试修改一下参数看看，并且保证你读取的是该配置文件

**Comment by flower-elf** [comment]
> 
> 
> 你尝试修改一下参数看看，并且保证你读取的是该配置文件

感谢，问题已经solve
